sudo: required
services:
    - docker
    
before_install:
    - docker build -t playmingz/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true playmingz/react-test npm test -- --coverage
    
after_success:
    - docker build -t playmingz/multi-client ./client
    - docker build -t playmingz/multi-nginx ./nginx
    - docker build -t playmingz/multi-server ./server
    - docker build -t playmingz/multi-worker ./worker
    
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push them to Docker Hub.
    - docker push playmingz/multi-client
    - docker push playmingz/multi-nginx
    - docker push playmingz/multi-server
    - docker push playmingz/multi-worker
    